// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using transaccionesBancarias;

#nullable disable

namespace transaccionesBancarias.Migrations
{
    [DbContext(typeof(TransaccionesContext))]
    [Migration("20240416154449_AccountNumber3")]
    partial class AccountNumber3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("transaccionesBancarias.Models.Cuenta", b =>
                {
                    b.Property<int?>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("account_number");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("AccountNumber"));

                    b.Property<int>("InitialBalance")
                        .HasColumnType("int")
                        .HasColumnName("initial_balance");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("owner_name");

                    b.HasKey("AccountNumber");

                    b.ToTable("Cuenta", (string)null);

                    b.HasData(
                        new
                        {
                            AccountNumber = 1,
                            InitialBalance = 1000,
                            OwnerName = "Richard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
