// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using transaccionesBancarias;

#nullable disable

namespace transaccionesBancarias.Migrations
{
    [DbContext(typeof(TransaccionesContext))]
    [Migration("20240416000553_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("transaccionesBancarias.Models.Cuenta", b =>
                {
                    b.Property<int>("Cuenta_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cuenta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cuenta_Id"));

                    b.Property<int>("Initial_Balance")
                        .HasColumnType("int")
                        .HasColumnName("initial_balance");

                    b.Property<string>("Owner_Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("owner_name");

                    b.HasKey("Cuenta_Id");

                    b.ToTable("Cuenta", (string)null);

                    b.HasData(
                        new
                        {
                            Cuenta_Id = 1,
                            Initial_Balance = 1000,
                            Owner_Name = "Richard"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
